# Generated by Django 4.1.3 on 2022-11-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_club_play_position_person_birthdate_delete_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='team_pic',
            field=models.ImageField(blank=True, default='defaultimg.png', null=True, upload_to='', verbose_name='Team Image'),
        ),
    ]
